### ISSUE TITLE
No clearBatch() method in statements

### ISSUE THREAD

**Issue by jibin-tj** [blue-color/nodejdbc#16]
Hi

I was working with batch inserts of statements. For very larges batches, i need to break the batches into chunks and execute. But I couldn't find any clearBatch method in statements. It would be very helpful if clearBatch is implemented as production level codes needs to break down each batches to chunks.

**Comment by ceyhunkerti** [comment]
Hi, i've added `clearBatch`

btw. i'll migrate the sources to typescript and there will be some changes and more options like connection pooling. You'll have to change your code a little but i guess it'll just take a couple of minutes.
And it'll be a new [repo](https://github.com/blue-color/njdbc) and new package.

**Comment by jibin-tj** [comment]
Thank you.

Looking forward to your new package
