### ISSUE TITLE
cannot set date in preparedStatements 

### ISSUE THREAD

**Issue by jibin-tj** [blue-color/nodejdbc#17]
I couldn't find setDate method in preparedstatements and is unable to insert type Date in DB.

Please note there is an option to insert timestamp though

Please add the setDate method to preparedstatements.

**Comment by jibin-tj** [comment]
Hi 

I noticed there is a timestamp option. But please add setDate as this is very important.

**Comment by ceyhunkerti** [comment]
Hi, just added that one
