### ISSUE TITLE
addbatch method in statement.js throws error

### ISSUE THREAD

**Issue by jibin-tj** [blue-color/nodejdbc#8]
Hi
Using addBatch method in statement.js throws the following error
`[TypeError: this.statement.addBatchASync is not a function]`

Please note that addBatchSync method is working fine. I am also wondering whats the difference between these two .

**Comment by ceyhunkerti** [comment]
That should be `addBatchAsync` fixed the typo.

The methods ending with `Sync` executed synchronously. You can use them like;
` var numOfRec = stmt.executeUpdateSync(sql);`
For the other methods you have to handle the returned promise like;
    `db.getConnection().then(function(con){
      con.close();
   });`

But some methods like `isClosed` are exceptional. They do not end with `Sync` yet they are synchronous.

**Comment by jibin-tj** [comment]
Okay. Thank you

Closing this as the issue is fixed .
