### ISSUE TITLE
connection.close method invalidates all connections 

### ISSUE THREAD

**Issue by jibin-tj** [blue-color/nodejdbc#9]
Hi
Consider a case a where two concurrent requests are inserting data to DB. First request finishes the inserts and call `conn.close().` This will make the second / all live request fail. 
I think the getconnection method returns the same connection reference for all request.

Is there any workaround. Does using `new nodejdbc`  in every request helps?

**Comment by ceyhunkerti** [comment]
Hi, there is a `newConnection` method, which returns a new connection each time. But you
have to store the reference to that connection in your code. if you use `newConnection` method you can NOT get the connection with `db.getConnection`

btw. if you are inserting to the same table, i don't think your rdbms will perform those requests in parallel.

**Comment by jibin-tj** [comment]
Thank you. So i guess getConnection not at all safe to use in webservice
